const fs = require('fs');
const path = require('path');
const chalk = require('chalk');
const _cloneDeep = require('lodash/cloneDeep');

const games = require('../server/db/gamesExtra.json');
const atari = require('./data/Atari2600.json'); // exclusives and launch titles
const xbox = require('./data/MicrosoftXbox.json'); // exclusives and launch titles
const xbox360 = require('./data/MicrosoftXbox360.json'); // exclusives and launch titles
const xboxOne = require('./data/MicrosoftXboxOne.json'); // exclusives and launch titles
const n64 = require('./data/Nintendo64.json'); // exclusives and launch titles
const nds = require('./data/NintendoDS.json'); // exclusives and launch titles
const nes = require('./data/NintendoEntertainmentSystem.json'); // exclusives, launch titles, hang tabs, four score, and black box
const ngb = require('./data/NintendoGameBoy.json'); // exlusives and launch titles
const gba = require('./data/NintendoGameBoyAdvance.json'); // exclusives and launch titles
const gbc = require('./data/NintendoGameBoyColor.json'); // exclusives and launch titles
const ngc = require('./data/NintendoGameCube.json'); // exclusives and launcht titles
const wii = require('./data/NintendoWii.json'); // exclusives and launch titles
const wiiu = require('./data/NintendoWiiU.json'); // exclusives and launch titles
const s32x = require('./data/Sega32x.json'); // exclusives and launch titles
const scd = require('./data/SegaCD.json'); // exclusives and launch titles
const sdc = require('./data/SegaDreamcast.json'); // exclusives and launch titles
const sgg = require('./data/SegaGameGear.json'); // exclusives and launch titles
const gen = require('./data/SegaGenesis.json'); // exclusives, launch titles, team player, and black box grid
const sst = require('./data/SegaSaturn.json'); // exclusives and launch titles
const ps1 = require('./data/SonyPlaystation.json'); // exclusives, launch titles, and multitap
const ps2 = require('./data/SonyPlaystation2.json'); // exclusives and launch titles
const psp = require('./data/SonyPlayStationPortable.json'); // exclusives and launch titles
const snes = require('./data/SuperNintendoEntertainmentSystem.json'); // exclusives, launch titles, and multitap
const tg16 = require('./data/TurboGrafx16.json'); // exclusives, launch titles, and multitap
