module.exports.consoleMatch = {
  NDS: { consoleName: 'Nintendo DS', consoleId: 20 },
  Saturn: { consoleName: 'Sega Saturn', consoleId: 32 },
  Genesis: { consoleName: 'Sega Mega Drive/Genesis', consoleId: 29 },
  'Master System': { consoleName: 'Sega Master System', consoleId: 64 },
  'Game Gear': { consoleName: 'Sega Game Gear', consoleId: 35 },
  PS3: { consoleName: 'PlayStation 3', consoleId: 3 },
  '3DO': { consoleName: '3DO Interactive Multiplayer', consoleId: 50 },
  Wii: { consoleName: 'Wii', consoleId: 5 },
  GameCube: { consoleName: 'Nintendo GameCube', consoleId: 21 },
  Intellivision: { consoleName: 'Intellivision', consoleId: 67 },
  '3DS': { consoleName: 'Nintendo 3DS', consoleId: 37 },
  'Atari 5200': { consoleName: 'Atari 5200', consoleId: 66 },
  PS4: { consoleName: 'PlayStation 4', consoleId: 48 },
  Dreamcast: { consoleName: 'Dreamcast', consoleId: 23 },
  'Sega CD': { consoleName: 'Sega CD', consoleId: 78 },
  GBA: { consoleName: 'Game Boy Advance', consoleId: 24 },
  Xbox: { consoleName: 'Xbox', consoleId: 11 },
  Switch: { consoleName: 'Nintendo Switch', consoleId: 130 },
  'Xbox One': { consoleName: 'Xbox One', consoleId: 49 },
  'Atari 7800': { consoleName: 'Atari 7800', consoleId: 60 },
  '32X': { consoleName: 'Sega 32X', consoleId: 30 },
  NES: { consoleName: 'Nintendo Entertainment System (NES)', consoleId: 18 },
  'Game Boy': { consoleName: 'Game Boy', consoleId: 33 },
  'Game Boy Color': { consoleName: 'Game Boy Color', consoleId: 22 },
  N64: { consoleName: 'Nintendo 64', consoleId: 4 },
  SNES: { consoleName: 'Super Nintendo Entertainment System (SNES)', consoleId: 19 },
  PS2: { consoleName: 'PlayStation 2', consoleId: 8 },
  Jaguar: { consoleName: 'Atari Jaguar', consoleId: 62 },
  'Wii U': { consoleName: 'Wii U', consoleId: 41 },
  TG16: { consoleName: 'TurboGrafx-16/PC Engine', consoleId: 86 },
  PS1: { consoleName: 'PlayStation', consoleId: 7 },
  'Xbox 360': { consoleName: 'Xbox 360', consoleId: 12 },
  PSP: { consoleName: 'PlayStation Portable', consoleId: 38 },
  'Atari 2600': { consoleName: 'Atari 2600', consoleId: 59 }
};
